import bgVideo from '../../public/Bg-Video.mp4'
import styles from './page.module.css'
import Link from 'next/link'
import Image from 'next/image'
import photo from '../../public/carbon-gas2.jpg'
import Img1 from '../../public/img10.jpg'
import Img2 from '../../public/img13.jpg'

export default function Home() {
  return (
    <div className='container'>
      <video src={bgVideo} autoPlay loop muted alt='bg image' className={styles.bgHome} />
        
      <div className={styles.heading}>
         <h1>Welcome </h1>
         <h1>to Carbon World</h1>
         <p>From cooking a pot roast to jetting away for the weekend, the choices you make in your day-to-day life leave a mark on the environment. Reduce carbon footprint and prevent climate change.</p>
         
         <div className={styles.btn}>
            <Link href='/calculate/carbon-calculator'>
              <button href='/calculate/carbon-calculate' className={styles.button}>Calculate</button>
            </Link>
          </div>

          <div className={styles.homeBody}>
            <div className={styles.wrapper}>
              <div className={styles.leftside}>
                <Image src={photo} width={600} height={600} alt='carbon survey' priority="true"></Image>
              </div>
              <div className={styles.rightside}>
                <h2>What is Carboon Footprint?</h2>
                <hr className={styles.line} />
                <p>A carbon footprint is the total amount of greenhouse gases including carbon dioxide and 
                  methane that are generated by our actions.
                </p>
                <p>The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, 
                  the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, 
                  the average global carbon footprint per year needs to drop to under 2 tons by 2050.
                </p>
                <p>Lowering individual carbon footprints from 16 tons to 2 tons doesnt happen overnight! By making small changes to our actions, 
                  like eating less meat, taking fewer connecting flights and line drying our clothes, we can start making a big difference.
                </p>
              </div>
            </div>
          </div>
          <section class=" bg-white dark:bg-gray-900">
            <div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
                <div class="max-w-screen-md">
                    <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Lets find more that brings us together.</h2>
                    <p class="mb-8 font-light text-gray-500 sm:text-xl dark:text-gray-400">Flowbite helps you connect with friends, family and communities of people who share your interests. Connecting with your friends and family as well as discovering new ones is easy with features like Groups, Watch and Marketplace.</p>
                    <div class="flex flex-col space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
                        <a href="#" class="inline-flex items-center justify-center px-4 py-2.5 text-base font-medium text-center text-white bg-primary-700 rounded-lg hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
                            Get started
                        </a>
                        <a href="#" class="inline-flex items-center justify-center px-4 py-2.5 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
                            <svg class="mr-2 -ml-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z"></path></svg>
                            View more
                        </a>  
                    </div>
                </div>
            </div>
          </section>
          <div className="bg-white dark:bg-gray-900">
            <div className="gap-32 space-between items-center py-8 px-6 mx-auto max-w-screen-xl lg:grid lg:grid-cols-2 lg:py-16 lg:px-6">
                <div className="sm:text-lg">
                    <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Calculate Your Carbon Footprint</h2>
                    <p className="mb-4">You can figure out how much your actions affect greenhouse gases by using a carbon footprint calculator. A carbon footprint is the total amount of carbon dioxide released into the atmosphere as a result of human activities. Your carbon footprint is the total carbon dioxide released due 
                      to your individual activities. Your households carbon footprint is the total carbon dioxide released by your home and all the people who live there. A carbon footprint calculator typically takes into account the greenhouse gases you produce at home and while traveling. It can also include the greenhouse 
                      gases produced to transport and make the food you eat and the things you buy.
                    </p>
                </div>
                <div className="grid grid-cols-2 gap-5 mt-8">
                    <Image className="w-full rounded-lg" src={Img1} alt="office content 1" />
                    <Image className="mt-4 w-full lg:mt-12 rounded-lg" src={Img2}  alt="office content 2" />
                </div>
            </div>
          </div>
      </div> 
    </div>
  )
}
